### ISSUE TITLE
Equations enclosed by single $ are not referenced

### ISSUE THREAD

**Issue by mickley** [lierdakil/pandoc-crossref#49] opened 2016-01-11 18:51 UTC
This works and displays as an equation on its own line:
```
$$(a^2 + b^2 = c^2)/\pi$$ {#eq:equation2}
```

This displays an inline equation, but it's not referenced, and saying [@eq:equation3] leads to eq. ??
```
$(a^2 + b^2 = c^2)/\pi$ {#eq:equation3}
```

**Comment by lierdakil** [comment] 2016-01-11 20:28
This is by design. Not entirely sure of what you expect inline equation to be rendered as, but I sure have no idea on how one would reference an inline equation unambiguously.

**Comment by mickley** [comment] 2016-01-11 21:01
Well, one use example is that inline equations don't get centered in the writers, they're left-aligned.  

So one could still have an in-line equation on its own line and reference it as any other equation.  

I suppose there may be a workaround for this using $$'ed equations, but I'm not aware of it.  

Couldn't one just have something like this: 1+2 (1) and then refer back to it later?  If that's not the intended behavior, the user can choose not to add a reference to the inline equation.

**Comment by lierdakil** [comment] 2016-07-15 08:01
Okay, so after some further investigation, it's impossible to do that with LaTeX output without some dubious dark LaTeX magic. So I'm closing this as wontfix. If you want display math to be left-aligned, just use css/LaTeX/whatever styling.

**Closed by lierdakil** 2016-07-15 08:01 UTC
Labels: enhancement, wontfix
