### ISSUE TITLE
Labels in align / eqnarray environment?

### ISSUE THREAD

**Issue by UlyssesZh** [lierdakil/pandoc-crossref#412] opened 2023-11-06 01:34 UTC
```latex
\begin{align}
    a\nonumber\\
    \label{b}b\\
    \label{c}c
\end{align}
```
How to do this?

**Comment by lierdakil** [comment] 2023-12-28 18:42
Long story short, you don't, but if you only need LaTeX/pdf output, you can just use LaTeX syntax. This is a duplicate of #131 so I'm closing it as such.

**Closed by lierdakil** 2023-12-28 18:42 UTC
