### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by mickley** [lierdakil/pandoc-crossref#36] opened 2015-09-30 01:13 UTC
For some reason, pandoc-crossref won't compile/install on Windows 7.  I've tried on several machines, first installing pandoc as a binary + the Haskell Platform, and then installing pandoc from source.  Pandoc works fine in both instances, but pandoc-crossref does not.

### Here's the install log:
```
Building pandoc-crossref-0.1.5.2...
Preprocessing library pandoc-crossref-0.1.5.2...
[ 1 of 17] Compiling Text.Pandoc.CrossRef.Util.Settings.Template ( src\Text\Pandoc\CrossRef\Util\Settings\Template.hs, dist\build\Text\Pandoc\CrossRef\Util\Settings\Template.o )
[ 2 of 17] Compiling Text.Pandoc.CrossRef.Util.Meta ( src\Text\Pandoc\CrossRef\Util\Meta.hs, dist\build\Text\Pandoc\CrossRef\Util\Meta.o )
[ 3 of 17] Compiling Text.Pandoc.CrossRef.Util.Template ( src\Text\Pandoc\CrossRef\Util\Template.hs, dist\build\Text\Pandoc\CrossRef\Util\Template.o )
[ 4 of 17] Compiling Text.Pandoc.CrossRef.Util.Util ( src\Text\Pandoc\CrossRef\Util\Util.hs, dist\build\Text\Pandoc\CrossRef\Util\Util.o )
[ 5 of 17] Compiling Text.Pandoc.CrossRef.Util.Accessor ( src\Text\Pandoc\CrossRef\Util\Accessor.hs, dist\build\Text\Pandoc\CrossRef\Util\Accessor.o )
[ 6 of 17] Compiling Text.Pandoc.CrossRef.References.Types ( src\Text\Pandoc\CrossRef\References\Types.hs, dist\build\Text\Pandoc\CrossRef\References\Types.o )
[ 7 of 17] Compiling Text.Pandoc.CrossRef.References.Accessors ( src\Text\Pandoc\CrossRef\References\Accessors.hs, dist\build\Text\Pandoc\CrossRef\References\Accessors.o )
[ 8 of 17] Compiling Text.Pandoc.CrossRef.Util.Settings.Gen ( src\Text\Pandoc\CrossRef\Util\Settings\Gen.hs, dist\build\Text\Pandoc\CrossRef\Util\Settings\Gen.o )
ghc.exe: unable to load package `hslua-0.4.1'
ghc.exe: warning: WSACleanup from ws2_32 is linked instead of __imp_WSACleanup
ghc.exe: warning: WSAStartup from ws2_32 is linked instead of __imp_WSAStartup
ghc.exe: warning: WSACleanup from ws2_32 is linked instead of __imp_WSACleanup
ghc.exe: warning: accept from ws2_32 is linked instead of __imp_accept
ghc.exe: warning: inet_ntoa from ws2_32 is linked instead of __imp_inet_ntoa
ghc.exe: warning: getnameinfo from ws2_32 is linked instead of __imp_getnameinfo
ghc.exe: warning: getaddrinfo from ws2_32 is linked instead of __imp_getaddrinfo
ghc.exe: warning: freeaddrinfo from ws2_32 is linked instead of __imp_freeaddrinfo
ghc.exe: warning: _tzset from msvcrt is linked instead of __imp__tzset
ghc.exe: warning: isalpha from msvcrt is linked instead of __imp_isalpha
ghc.exe: warning: GetVersionExA from kernel32 is linked instead of __imp_GetVersionExA
ghc.exe: warning: GetModuleHandleA from kernel32 is linked instead of __imp_GetModuleHandleA
ghc.exe: warning: GetProcAddress from kernel32 is linked instead of __imp_GetProcAddress
ghc.exe: warning: _snprintf from msvcrt is linked instead of __imp__snprintf
ghc.exe: warning: GetSystemInfo from kernel32 is linked instead of __imp_GetSystemInfo
ghc.exe: warning: GetSystemMetrics from user32 is linked instead of __imp_GetSystemMetrics
ghc.exe: warning: GetVersionExA from kernel32 is linked instead of __imp_GetVersionExA
ghc.exe: warning: _snprintf from msvcrt is linked instead of __imp__snprintf
ghc.exe: warning: GetSystemInfo from kernel32 is linked instead of __imp_GetSystemInfo
ghc.exe: warning: GetComputerNameA from kernel32 is linked instead of __imp_GetComputerNameA
ghc.exe: warning: CryptAcquireContextA from advapi32 is linked instead of __imp_CryptAcquireContextA
ghc.exe: warning: CryptGenRandom from advapi32 is linked instead of __imp_CryptGenRandom
ghc.exe: warning: _stat64 from msvcrt is linked instead of __imp__stat64
ghc.exe: warning: _open from msvcrt is linked instead of __imp__open
ghc.exe: warning: _stat64 from msvcrt is linked instead of __imp__stat64
ghc.exe: warning: tolower from msvcrt is linked instead of __imp_tolower
ghc.exe: warning: toupper from msvcrt is linked instead of __imp_toupper
ghc.exe: warning: isalpha from msvcrt is linked instead of __imp_isalpha
ghc.exe: warning: isalnum from msvcrt is linked instead of __imp_isalnum
ghc.exe: warning: isupper from msvcrt is linked instead of __imp_isupper
ghc.exe: warning: isgraph from msvcrt is linked instead of __imp_isgraph
ghc.exe: warning: isprint from msvcrt is linked instead of __imp_isprint
ghc.exe: warning: ispunct from msvcrt is linked instead of __imp_ispunct
ghc.exe: warning: iscntrl from msvcrt is linked instead of __imp_iscntrl
ghc.exe: warning: isupper from msvcrt is linked instead of __imp_isupper
ghc.exe: C:\Users\James\AppData\Roaming\cabal\x86_64-windows-ghc-7.10.2\hslua-0.4.1-DAXOloNJurRCYy4KgxvZeZ\HShslua-0.4.1-DAXOloNJurRCYy4KgxvZeZ.o: unknown symbol `mingw_getsp'
```

**Comment by lierdakil** [comment] 2015-09-30 01:15
Duplicate of #7

**Closed by lierdakil** 2015-09-30 01:15 UTC
